### ISSUE TITLE
Accuracy of other tasks.

### ISSUE THREAD

**Issue by tyler7585** [ethancaballero/Improved-Dynamic-Memory-Networks-DMN-plus#1]
Hello.
In DMN+, task 19(pathfinding) is almost solved. Can you tell me the your repo's accuracy of task 19? Did you reach that high accuracy?
Thank you  very much.

**Comment by ethancaballero** [comment]
I didn't test task 19 yet. If you want to test it for me, download repo and run this command in terminal while in Improved-Dynamic-Memory-Networks-DMN-plus folder:
`python main.py --network dmn_tied --mode train --babi_id 19`

It takes about a day to finish training on a normal laptop.

Make sure you redownload the repo. I just updated the parse argument in utils.py so that it pulls babi data from en-10k folder (the one the paper used when benchmarking tasks such as 19) instead of en (1k) folder.

Also, there's probably a way to increase the accuracy by a few percents by implementing dropout on the inputs in a manner similar to @therne's repo.
